---

- name: Remove nebula binary
  ansible.builtin.file:
    path: /usr/sbin/nebula
    state: absent
  become: true

- name: Remove nebula config directory
  ansible.builtin.file:
    path: /etc/nebula
    state: absent
  become: true

- name: Remove nebula systemd service
  ansible.builtin.file:
    path: /etc/systemd/system/nebula.service
    state: absent
